"""initial_schema

Revision ID: cced58321476
Revises: 
Create Date: 2026-10-09 02:28:04.136948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cced58321476'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('total_credits', sa.Integer(), nullable=False),
    sa.Column('catalog_status', sa.String(length=64), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_pages', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('choice_groups',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('program_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('required_credits', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'program_id')
    )
    op.create_index(op.f('ix_choice_groups_program_id'), 'choice_groups', ['program_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('program_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(length=128), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('choice_group_ids', sa.JSON(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('suggested_term', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'program_id', name='uq_course_code_program')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=False)
    op.create_index(op.f('ix_courses_program_id'), 'courses', ['program_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('program_id', sa.String(length=64), nullable=False),
    sa.Column('current_term', sa.Integer(), nullable=False),
    sa.Column('gpa_10', sa.Float(), nullable=False),
    sa.Column('accumulated_credits', sa.Integer(), nullable=False),
    sa.Column('target_track', sa.String(length=128), nullable=True),
    sa.Column('career_goal', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_program_id'), 'students', ['program_id'], unique=False)
    op.create_table('course_prerequisites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=32), nullable=False),
    sa.Column('program_id', sa.String(length=64), nullable=False),
    sa.Column('prerequisite_code', sa.String(length=32), nullable=False),
    sa.Column('clause_index', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_prerequisites_course_code'), 'course_prerequisites', ['course_code'], unique=False)
    op.create_index(op.f('ix_course_prerequisites_course_id'), 'course_prerequisites', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_prerequisites_prerequisite_code'), 'course_prerequisites', ['prerequisite_code'], unique=False)
    op.create_index(op.f('ix_course_prerequisites_program_id'), 'course_prerequisites', ['program_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('course_code', sa.String(length=32), nullable=False),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('term', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_code', 'term', name='uq_student_course_term')
    )
    op.create_index(op.f('ix_enrollments_course_code'), 'enrollments', ['course_code'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_table('recommendation_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('program_id', sa.String(length=64), nullable=False),
    sa.Column('passed_course_codes', sa.JSON(), nullable=False),
    sa.Column('whatif_weights', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_runs_program_id'), 'recommendation_runs', ['program_id'], unique=False)
    op.create_index(op.f('ix_recommendation_runs_student_id'), 'recommendation_runs', ['student_id'], unique=False)
    op.create_table('student_preferences',
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('weight_goal', sa.Float(), nullable=False),
    sa.Column('weight_track', sa.Float(), nullable=False),
    sa.Column('weight_perf', sa.Float(), nullable=False),
    sa.Column('weight_workload', sa.Float(), nullable=False),
    sa.Column('weight_hands_on', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('recommendation_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('course_code', sa.String(length=32), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('explanation_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['recommendation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_items_run_id'), 'recommendation_items', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_items_run_id'), table_name='recommendation_items')
    op.drop_table('recommendation_items')
    op.drop_table('student_preferences')
    op.drop_index(op.f('ix_recommendation_runs_student_id'), table_name='recommendation_runs')
    op.drop_index(op.f('ix_recommendation_runs_program_id'), table_name='recommendation_runs')
    op.drop_table('recommendation_runs')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_code'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_course_prerequisites_program_id'), table_name='course_prerequisites')
    op.drop_index(op.f('ix_course_prerequisites_prerequisite_code'), table_name='course_prerequisites')
    op.drop_index(op.f('ix_course_prerequisites_course_id'), table_name='course_prerequisites')
    op.drop_index(op.f('ix_course_prerequisites_course_code'), table_name='course_prerequisites')
    op.drop_table('course_prerequisites')
    op.drop_index(op.f('ix_students_program_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_courses_program_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_choice_groups_program_id'), table_name='choice_groups')
    op.drop_table('choice_groups')
    op.drop_table('programs')
    # ### end Alembic commands ###
